server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/csv_to_mysql?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
#      dialect:  org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
    show-sql: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
